### ISSUE TITLE
Please add controls property to Attribute

### ISSUE THREAD

**Issue by eehret** [sduck/Crm2013TypeScript#3]
The XRM api has this property but your typescript definition does not.

In my local copy I have added it as follows:

controls: ControlsCollection<Control>;

**Comment by sduck** [comment]
Thanks for the feedback.

Just had a quick look and I cannot see where it is missing. Could you specify a bit further and I will happily publish a fix

**Comment by eehret** [comment]
interface Attribute {
    addOnChange(ev: any): void;
    fireOnChange(): void;
    getAttributeType(): string;
    getFormat(): string;
    getInitialValue(): number;
    getIsDirty(): boolean;
    getMax(): number;
    getMaxLength(): number;
    getMin(): number;
    getName(): string;
    getOption(value: string): Object; // review
    getOption(value: number): Object; // review
    getOptions(): any[];
    getParent(): Entity;
    getPrecision(): number;
    getRequiredLevel(): string;
    getSelectedOption(): Option; // review
    getSubmitMode(): string;
    getText(): string;
    getUserPrivilege(): UserPrivilege; // review
    getValue(): any;
    removeOnChange(ev: any): void;
    setRequiredLevel(requirementLevel: string): void;
    setSubmitMode(SubmitMode: string): void; // review
    setValue(value: any);
    controls: ControlsCollection<Control>;
}


Last line was added by me to match what I was expecting from referring to Xrm API.

**Comment by eehret** [comment]
ugh sorry, that didn't come through properly. 

Last line should read
`controls: ControlsCollection<Control>;`
